# Game.create!([
#   {title: "Hollow Knight", box_art: "https://e.snmc.io/lk/l/x/d5895ebe101966c3ab99fc2da6bc4d53/5299152", about: "Hollow Knight is a classically styled 2D action adventure across a vast interconnected world. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and solve ancient mysteries at the kingdom's heart.", platforms: "Playstation 4, Nintendo Switch, Xbox One, macOS, Microsoft Windows, Linux", multiplayer: "No", esrb_rating: "E10+", content_description: "fantasy violence, mild blood", developer: "Team Cherry", publisher: "Team Cherry"},
#   {title: "Celeste", box_art: "https://www.mobygames.com/images/covers/l/452220-celeste-playstation-4-front-cover.jpg", about: "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the mystery of the mountain.", platforms: "Playstation 4, Nintendo Switch, Xbox One, macOS, Microsoft Windows, Linux, Stadia", multiplayer: "No", esrb_rating: "E10+", content_description: "fantasy violence, alcohol reference, mild language", developer: "Matt Makes Games", publisher: "Matt Makes Games"}
# ])

# UserGame.create!([
#   {user_id: 1, game_id: 1, status: "completed", rating: 10, review: "This game is incredible. Seriously, everything about it is absolutely perfect. Just play it, ya dingus!", completion_hours: 8, completion_minutes: 10},
#   {user_id: 1, game_id: 2, status: "completed", rating: 10, review: "This game is an absolute gem of a platformer. Textbook execution, phenomenal style. Just play it, ya dingus!", completion_hours: 24, completion_minutes: nil},
#   {user_id: 2, game_id: 1, status: "playing", rating: nil, review: nil, completion_hours: nil, completion_minutes: nil},
#   {user_id: 6, game_id: 1, status: "completed", rating: 10, review: "Great game!", completion_hours: 8, completion_minutes: 48}
# ])

# User.create!([
#   {name: "tyler", email: "tyler@example.com", password_digest: "$2a$12$jpZ2dgAgz2HF7xv7334/OOT9dB01nDQ4R6lp8X9cYgq8xsabTN6VG"},
#   {name: "llianna", email: "llianna@example.com", password_digest: "$2a$12$cLZh/TQwvf7s/0O4iEVBSe1fILI7kYHerLXg70LwjFGgFOcPftlCS"},
#   {name: "justin", email: "justin@example.com", password_digest: "$2a$12$parxIf0Xyxw9TgDPrVDoYeyYDkN1.TH46KOAvdRigJYrC9WbzIWai"},
#   {name: "markell", email: "markell@example.com", password_digest: "$2a$12$r7S3G81xD1xJ2A5I703A5eTZYHQn9xa1P8GORekmB784p3d4WsQ/e"}
# ])

# Game.create!([
#   { title: "Valheim", box_art: "https://static-cdn.jtvnw.net/ttv-boxart/Valheim.jpg", about: "Valheim is a game about exploring a huge fantasy world inspired by norse mythology and viking culture. You start your adventure at the relatively peaceful center of Valheim. The further from the center you travel, the more challenging the world becomes. But you will also find more valuable materials that you can use to craft deadlier weapons and sturdier armor. You will also build your own viking strongholds and outposts all over the world. Eventually you will build a mighty longship and sail the great oceans in search of exotic lands … but be wary of sailing too far...", platforms: "macOS, Microsoft Windows, Linux", multiplayer: "Online Co-op", esrb_rating: "Not Rated", content_description: "N/A", developer: "Dvoid, Richard Svensson", publisher: "Coffee Stain" },
#   { title: "It Takes Two", box_art: "https://hardcore-gamer.s3.amazonaws.com/uploads/2021/03/It_Takes_Two_box_art.jpg", about: "Bring your favorite co-op partner and together step into the shoes of May and Cody. As the couple is going through a divorce, through unknown means their minds are transported into two dolls which their daughter, Rose, made to represent them. Now they must reluctantly find a way to get back into their bodies, a quest which takes them through the most wild, unexpected and fantastical journey imaginable.", platforms: "macOS, Microsoft Windows, Linux", multiplayer: "Online Co-op, Local Co-op", esrb_rating: "E10+", content_description: "Animated Blood, Comic Mischief, Fantasy Violence, Language", developer: "Hazelight, Mohammad Almajali", publisher: "Electronic Arts, Mohammad Almajali" },
#   { title: "Monster Hunter Rise", box_art: "https://gamepreorders.com/wp-content/uploads/2020/09/cover-art-10.jpg", about: "Set in the ninja-inspired land of Kamura Village, explore lush ecosystems and battle fearsome monsters to become the ultimate hunter. It’s been half a century since the last calamity struck, but a terrifying new monster has reared its head and threatens to plunge the land into chaos once again.", platforms: "Microsoft Windows, Nintendo Switch", multiplayer: "Online Co-op", esrb_rating: "T", content_description: "Violence, Alcohol Reference, Blood", developer: "Capcom", publisher: "Capcom" },
# ])
